/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package imagej.envisaje.imageframe;

import com.sun.media.jai.widget.DisplayJAI;
import java.awt.BorderLayout;
import java.awt.Container;
import java.io.File;
import java.io.IOException;
import java.util.logging.Logger;
import javax.media.jai.JAI;
import javax.media.jai.PlanarImage;
import javax.swing.JFileChooser;
import javax.swing.JScrollPane;
import org.openide.util.Exceptions;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.ImageUtilities;
import org.netbeans.api.settings.ConvertAsProperties;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//imagej.imageframe//ImgDisplay//EN",
autostore = false)
public final class ImgDisplayTopComponent extends TopComponent {

  private static ImgDisplayTopComponent instance;
  /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";
  private static final String PREFERRED_ID = "ImgDisplayTopComponent";
//To select the path of image file
  private File file;
//To load the image file
  private PlanarImage srcImage = null;
//To display the image file
  //private DisplayJAI srcdj = null;
  NavigableImagePanel srcdj = null;
  private JScrollPane srcScrollPaneImage = null;
//To choose file by browsing
  private JFileChooser FileChooser = new JFileChooser();
//This flag will be set once image is loaded for the first time
  public boolean flag = false;

  public ImgDisplayTopComponent() {
    initComponents();
    setName(NbBundle.getMessage(ImgDisplayTopComponent.class, "CTL_ImgDisplayTopComponent"));
    setToolTipText(NbBundle.getMessage(ImgDisplayTopComponent.class, "HINT_ImgDisplayTopComponent"));
//        setIcon(ImageUtilities.loadImage(ICON_PATH, true));

  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageFrame = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        imageMenu = new javax.swing.JMenu();
        Open = new javax.swing.JMenuItem();

        setLayout(new java.awt.BorderLayout());

        ImageFrame.setVisible(true);

        org.openide.awt.Mnemonics.setLocalizedText(imageMenu, org.openide.util.NbBundle.getMessage(ImgDisplayTopComponent.class, "ImgDisplayTopComponent.imageMenu.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(Open, org.openide.util.NbBundle.getMessage(ImgDisplayTopComponent.class, "ImgDisplayTopComponent.Open.text")); // NOI18N
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        imageMenu.add(Open);

        jMenuBar1.add(imageMenu);

        ImageFrame.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout ImageFrameLayout = new javax.swing.GroupLayout(ImageFrame.getContentPane());
        ImageFrame.getContentPane().setLayout(ImageFrameLayout);
        ImageFrameLayout.setHorizontalGroup(
            ImageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        ImageFrameLayout.setVerticalGroup(
            ImageFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        add(ImageFrame, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

  private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
    int returnVal = FileChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
      //Initialise file object
      file = FileChooser.getSelectedFile();
      //Display the image
      displayimage(file);
    }
  }//GEN-LAST:event_OpenActionPerformed
  public void displayimage(File path) {
    // Load the image which file name was passed as the first argument to the
    // application.
    srcImage = JAI.create("fileload", path.getPath());
    //When image is loaded for first time...
    if (flag == false) {
      // Get the JFrame's ContentPane.
      Container contentPane = ImageFrame.getContentPane();
      contentPane.setLayout(new BorderLayout());
            try {
                // Create an instance of DisplayJAI.
                //srcdj = new DisplayJAI(srcImage);
                srcdj = new NavigableImagePanel(srcImage.getAsBufferedImage());
            } catch (IOException ex) {
                Exceptions.printStackTrace(ex);
            }
      // Add to the JFrame's ContentPane an instance of JScrollPane containing the DisplayJAI instance.
      srcScrollPaneImage = new JScrollPane(srcdj);
      //srcScrollPaneImage
      contentPane.add(srcScrollPaneImage, BorderLayout.CENTER);
      ImageFrame.setVisible(true); // show the frame.
      ImageFrame.validate();
      flag = true;
    } //If any image was already loaded before
    else {
      // srcdj.set(srcImage);
      srcdj.setImage(srcImage.getAsBufferedImage());
    }
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame ImageFrame;
    private javax.swing.JMenuItem Open;
    private javax.swing.JMenu imageMenu;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

  /**
   * Gets default instance. Do not use directly: reserved for *.settings files only,
   * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
   * To obtain the singleton instance, use {@link #findInstance}.
   */
  public static synchronized ImgDisplayTopComponent getDefault() {
    if (instance == null) {
      instance = new ImgDisplayTopComponent();
    }
    return instance;
  }

  /**
   * Obtain the ImgDisplayTopComponent instance. Never call {@link #getDefault} directly!
   */
  public static synchronized ImgDisplayTopComponent findInstance() {
    TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
    if (win == null) {
      Logger.getLogger(ImgDisplayTopComponent.class.getName()).warning(
              "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
      return getDefault();
    }
    if (win instanceof ImgDisplayTopComponent) {
      return (ImgDisplayTopComponent) win;
    }
    Logger.getLogger(ImgDisplayTopComponent.class.getName()).warning(
            "There seem to be multiple components with the '" + PREFERRED_ID
            + "' ID. That is a potential source of errors and unexpected behavior.");
    return getDefault();
  }

  @Override
  public int getPersistenceType() {
    return TopComponent.PERSISTENCE_ALWAYS;
  }

  @Override
  public void componentOpened() {
    // TODO add custom code on component opening
  }

  @Override
  public void componentClosed() {
    // TODO add custom code on component closing
  }

  void writeProperties(java.util.Properties p) {
    // better to version settings since initial version as advocated at
    // http://wiki.apidesign.org/wiki/PropertyFiles
    p.setProperty("version", "1.0");
    // TODO store your settings
  }

  Object readProperties(java.util.Properties p) {
    if (instance == null) {
      instance = this;
    }
    instance.readPropertiesImpl(p);
    return instance;
  }

  private void readPropertiesImpl(java.util.Properties p) {
    String version = p.getProperty("version");
    // TODO read your settings according to their version
  }

  @Override
  protected String preferredID() {
    return PREFERRED_ID;
  }
}
