#release configuration
#Sat Jun 27 22:06:26 CDT 2026
projectVersionPolicyId=default
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
pinExternals=false
project.scm.net.imagej\:imagej.developerConnection=scm\:git\:git@github.com\:imagej/imagej2
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
project.dev.net.imagej\:imagej=2.18.1-SNAPSHOT
exec.activateProfiles=deploy-to-scijava
pushChanges=false
project.rel.net.imagej\:imagej=2.18.0
project.scm.net.imagej\:imagej.tag=HEAD
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
releaseStrategyId=default
completedPhase=end-release
scm.url=scm\:git\:https\://github.com/imagej/imagej2
scm.developmentCommitComment=@{prefix} prepare for next development iteration
project.scm.net.imagej\:imagej.url=https\://github.com/imagej/imagej2
project.scm.net.imagej\:imagej.connection=scm\:git\:https\://github.com/imagej/imagej2
exec.additionalArguments=-Dgpg.skip\=true 
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.tag=imagej-2.18.0
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.pomFileName=pom.xml
