package org.imagejdev.pluginloader;

import java.util.logging.Logger;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.ImageUtilities;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.windows.IOProvider;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//org.imagejdev.pluginloader//PluginLoader//EN", autostore = false)
public final class PluginLoaderTopComponent extends TopComponent {
    private static PluginLoaderTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";
    private static final String PREFERRED_ID = "PluginLoaderTopComponent";

    public PluginLoaderTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(PluginLoaderTopComponent.class, "CTL_PluginLoaderTopComponent"));
        setToolTipText(NbBundle.getMessage(PluginLoaderTopComponent.class, "HINT_PluginLoaderTopComponent"));
//        setIcon(ImageUtilities.loadImage(ICON_PATH, true));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized PluginLoaderTopComponent getDefault() {
        if (instance == null) {
            instance = new PluginLoaderTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the PluginLoaderTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized PluginLoaderTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(PluginLoaderTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof PluginLoaderTopComponent) {
            return (PluginLoaderTopComponent) win;
        }
        Logger.getLogger(PluginLoaderTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID
                + "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        // custom code on component opening
        IOProvider.getDefault().getIO("PluginLoader", false).getOut().println("componentOpened()...");
    }

    @Override
    public void componentClosed() {
        // custom code on component closing
        IOProvider.getDefault().getIO("PluginLoader", false).getOut().println("componentClosed()...");

    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    Object readProperties(java.util.Properties p) {
        if (instance == null) {
            instance = this;
        }
        instance.readPropertiesImpl(p);
        return instance;
    }

    private void readPropertiesImpl(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }
}
