/*
 * #%L
 * ImageJ software for multidimensional image processing and analysis.
 * %%
 * Copyright (C) 2009 - 2012 Board of Regents of the University of
 * Wisconsin-Madison, Broad Institute of MIT and Harvard, and Max Planck
 * Institute of Molecular Cell Biology and Genetics.
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * 
 * The views and conclusions contained in the software and documentation are
 * those of the authors and should not be interpreted as representing official
 * policies, either expressed or implied, of any organization.
 * #L%
 */

package imagej.legacy;

import ij.ImagePlus;
import imagej.legacy.patches.Utils;
import imagej.legacy.plugin.LegacyCommand;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * <p>
 * The legacy output tracker is responsible for tracking important changes to
 * the IJ1 environment as a result of running a plugin. Important changes
 * include newly created {@link ImagePlus}es and {@link ImagePlus}es whose
 * window has closed.
 * <p>
 * The design maintains a pair of lists for each running {@link LegacyCommand}.
 * This is done by {@link ThreadGroup} rather than by {@link Thread}.
 * 
 * @author Curtis Rueden
 * @author Barry DeZonia
 */
public class LegacyOutputTracker {

	// -- instance variables --

	/**
	 * Used to provide one list of {@link ImagePlus} per {@link LegacyCommand}
	 * derived thread group.
	 */
	private static Map<ThreadGroup, Set<ImagePlus>> outputImps =
		new HashMap<ThreadGroup, Set<ImagePlus>>();

	/**
	 * Used to provide one list of {@link ImagePlus} per {@link LegacyCommand}
	 * derived thread group.
	 */
	private static Map<ThreadGroup, Set<ImagePlus>> closedImps =
		new HashMap<ThreadGroup, Set<ImagePlus>>();

	/**
	 * Tracks which {@link ImagePlus}es have their close() method initiated by
	 * ImageJ.
	 */
	private static Set<ImagePlus> modernImageJInitiatedClosings =
		new HashSet<ImagePlus>();

	// -- public interface --

	// -- METHODS FOR TRACKING OUTPUTS --

	/**
	 * Gets a list of the currently known output {@link ImagePlus}es generated by
	 * all the threads associated with a single {@link LegacyCommand}. This code
	 * is thread safe.
	 */
	public static synchronized ImagePlus[] getOutputImps() {
		return toArray(outputImps);
	}

	/**
	 * Add an {@link ImagePlus} to the current output list. Output lists are
	 * associated with {@link ThreadGroup}s hatched by {@link LegacyCommand}s.
	 * This code is thread safe.
	 */
	public static synchronized void addOutput(ImagePlus imp) {
		add(outputImps, imp);
	}

	/**
	 * Remove an {@link ImagePlus} from the current output list. Output lists are
	 * associated with {@link ThreadGroup}s hatched by {@link LegacyCommand}s.
	 * This code is thread safe.
	 */
	public static synchronized void removeOutput(ImagePlus imp) {
		remove(outputImps, imp);
	}

	/**
	 * Return true if the current output list contains the given {@link ImagePlus}
	 * . This code is thread safe.
	 */
	public static synchronized boolean containsOutput(ImagePlus imp) {
		return contains(outputImps, imp);
	}

	/**
	 * Clears the list of {@link ImagePlus}es stored in the current output list.
	 * This code is thread safe.
	 */
	public static synchronized void clearOutputs() {
		clear(outputImps);
	}

	// -- METHODS FOR TRACKING CLOSED IMAGES --

	/**
	 * Gets a list of the currently known closed {@link ImagePlus}es generated by
	 * all the threads associated with a single {@link LegacyCommand}. This code
	 * is thread safe.
	 */
	public static synchronized ImagePlus[] getClosedImps() {
		return toArray(closedImps);
	}

	/**
	 * Add an {@link ImagePlus} to the current closed list. Closed lists are
	 * associated with {@link ThreadGroup}s hatched by {@link LegacyCommand}s.
	 * This code is thread safe.
	 */
	public static synchronized void addClosed(ImagePlus imp) {
		add(closedImps, imp);
	}

	/**
	 * Remove an {@link ImagePlus} from the current closed list. Closed lists are
	 * associated with {@link ThreadGroup}s hatched by {@link LegacyCommand}s.
	 * This code is thread safe.
	 */
	public static synchronized void removeClosed(ImagePlus imp) {
		remove(closedImps, imp);
	}

	/**
	 * Return true if the current closed list contains the given {@link ImagePlus}
	 * . This code is thread safe.
	 */
	public static synchronized boolean containsClosed(ImagePlus imp) {
		return contains(closedImps, imp);
	}

	/**
	 * Clears the list of {@link ImagePlus}es stored in the current closed list.
	 * This code is thread safe.
	 */
	public static synchronized void clearClosed() {
		clear(closedImps);
	}

	// -- METHODS FOR TRACKING MODERN IMAGEJ INITIATED CLOSES --

	/**
	 * Informs tracker that ImageJ has initiated the close() of an
	 * {@link ImagePlus}.
	 */
	public static synchronized void closeInitiatedByModernImageJ(
		final ImagePlus imp)
	{
		modernImageJInitiatedClosings.add(imp);
	}

	/**
	 * Informs tracker that ImageJ has finished the close() of an
	 * {@link ImagePlus}.
	 */
	public static synchronized void closeCompletedByModernImageJ(
		final ImagePlus imp)
	{
		modernImageJInitiatedClosings.remove(imp);
	}

	/**
	 * Returns true if a given {@link ImagePlus} is currently being closed by
	 * ImageJ.
	 */
	public static synchronized boolean isBeingClosedByModernImageJ(
		final ImagePlus imp)
	{
		return modernImageJInitiatedClosings.contains(imp);
	}

	// -- helpers --

	private static ThreadGroup getGroup() {
		return Utils.findLegacyThreadGroup(Thread.currentThread());
	}

	private static void add(Map<ThreadGroup, Set<ImagePlus>> map, ImagePlus imp) {
		ThreadGroup legacyGroup = getGroup();
		if (legacyGroup == null) return;
		Set<ImagePlus> set = map.get(legacyGroup);
		if (set == null) {
			set = new HashSet<ImagePlus>();
			map.put(legacyGroup, set);
		}
		set.add(imp);
	}

	private static void clear(Map<ThreadGroup, Set<ImagePlus>> map) {
		ThreadGroup legacyGroup = getGroup();
		if (legacyGroup == null) return;
		Set<ImagePlus> imps = map.get(legacyGroup);
		if (imps != null) imps.clear();
	}

	private static boolean contains(Map<ThreadGroup, Set<ImagePlus>> map,
		ImagePlus imp)
	{
		ThreadGroup legacyGroup = getGroup();
		if (legacyGroup == null) return false;
		Set<ImagePlus> imps = map.get(legacyGroup);
		if (imps == null) return false;
		return imps.contains(imp);
	}

	private static void
		remove(Map<ThreadGroup, Set<ImagePlus>> map, ImagePlus imp)
	{
		ThreadGroup legacyGroup = getGroup();
		if (legacyGroup == null) return;
		Set<ImagePlus> set = map.get(legacyGroup);
		if (set != null) set.remove(imp);
	}

	private static ImagePlus[] toArray(Map<ThreadGroup, Set<ImagePlus>> map) {
		ImagePlus[] emptyList = new ImagePlus[0];
		ThreadGroup legacyGroup = getGroup();
		if (legacyGroup == null) return emptyList;
		Set<ImagePlus> set = map.get(legacyGroup);
		if (set == null) return emptyList;
		return set.toArray(emptyList);
	}
}
